tacocloud:
  email:
    imap-host: imap.gmail.com
    imap-port: 993
    username: lethabo.mosoathupa8@gmail.com
    password: 
    mailbox: INBOX
    poll-rate: 30000
  api:
    url: http://localhost:8080/api/orders